### ISSUE TITLE
Can't serve using a custom config file

### ISSUE THREAD

**Issue by raffomania** [getzola/zola#294]
Starting gutenberg like so:

    gutenberg --config config.dev.toml serve

I get the following output:
```
Building site...
-> Creating 0 pages (0 orphan) and 0 sections
Done in 14ms.

Error: Can't watch the `config.toml` file. Does it exist?
Reason: entity not found
Reason: No such file or directory (os error 2)
```

**Comment by Keats** [comment]
Which version of Gutenberg are you using? It should be working in the latest version (0.3.3)

**Comment by raffomania** [comment]
I'm using version 0.3.3, and still get the error. You should be able to easily reproduce this:

    gutenberg init test
    cd test
    mv config.toml config.dev.toml
    gutenberg --config config.dev.toml serve

**Comment by Keats** [comment]
Thanks, that's the watcher that was expecting a `config.toml` file to be present, I should have read the error message in the first post more carefully >_>
It's fixed in the patch above that will be in 0.4.0

**Comment by raffomania** [comment]
Thanks :)
