### ISSUE TITLE
robots.txt template not taken into account

### ISSUE THREAD

**Issue by greizgh** [getzola/zola#443]
On a fresh projet , when setting a custom robots.txt template, the generated robots.txt seems to be the default one.

Steps to reproduce:
```
$ gutenberg init customRobots
$ cd customRobots
$ echo "test" > templates/robots.txt
$ gutenberg build
$ cat public/robots.txt
User-agent: *
```

Expected result: `public/robots.txt` contains "test"

This has been tested with gutenberg 0.4.2 as well as next version (9461769bccef9e77e89b684a4d3231d4f5f0aa38)

**Comment by Keats** [comment]
Should be fixed in the next branch now

**Comment by greizgh** [comment]
The issue is still reproducible on the next branch (99215a4523754fb273b5ef4fd52e87ae975a69d5).
Also, I commented on your commit (https://github.com/Keats/gutenberg/commit/a11f8232decf54f8e6b445a6e914fb2d13fcb53e#r30713859): the test case seems the opposite of what we want?

**Comment by Keats** [comment]
Should be working for real now!
